version       = "0.1.0"
author        = "dneumann42"
description   = "Shui - A simple GUI framework"
license       = "MIT"
srcDir        = "src"

requires "nim >= 2.0.0"
requires "patty >= 0.3.4"
requires "vmath >= 1.2.0"
requires "bumpy >= 1.1.0"
requires "macroutils"
requires "stack_strings"
requires "pretty"
requires "cssgrid"
